name: Release Charts

on:
  push:
    branches: [setup-chart-release]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Add helm dependencies
        run: |
          helm repo add bitnami "https://charts.bitnami.com/bitnami"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"


      - name: Push Helm Chart to Artifactory
        run: |
          helm registry login ${{ secrets.ARTIFACTORY_URL }} --username "apikey" --password "${{ secrets.ARTIFACTORY_API_KEY }}"
          helm push tooljet-*.tgz oci://${{ secrets.ARTIFACTORY_URL }}/${{ secrets.ARTIFACTORY_REPO }}

      - name: Update Helm Index for GitHub Pages
        run: |
          helm repo index --url https://slancerk.github.io/helm-charts-artifactory-test/charts/tooljet/ --merge charts/tooljet/index.yaml charts/tooljet/
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add charts/tooljet/index.yaml
          git commit -m "Update Helm index.yaml for new release"
          git push origin main
